"""Initial migration: create user_stories, test_plans, and test_cases tables

Revision ID: 65a797297c5f
Revises: 
Create Date: 2026-01-19 21:13:07.587461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a797297c5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('story_type', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stories_id'), 'user_stories', ['id'], unique=False)
    op.create_index(op.f('ix_user_stories_story_id'), 'user_stories', ['story_id'], unique=True)
    op.create_table('test_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_story_id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('high_priority_count', sa.Integer(), nullable=True),
    sa.Column('medium_priority_count', sa.Integer(), nullable=True),
    sa.Column('low_priority_count', sa.Integer(), nullable=True),
    sa.Column('analysis_markdown', sa.Text(), nullable=False),
    sa.Column('test_plan_markdown', sa.Text(), nullable=False),
    sa.Column('download_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_story_id'], ['user_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_plans_download_token'), 'test_plans', ['download_token'], unique=True)
    op.create_index(op.f('ix_test_plans_id'), 'test_plans', ['id'], unique=False)
    op.create_index(op.f('ix_test_plans_user_story_id'), 'test_plans', ['user_story_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_plan_id', sa.Integer(), nullable=False),
    sa.Column('tc_id', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('precondition', sa.Text(), nullable=True),
    sa.Column('expected_validation', sa.Text(), nullable=False),
    sa.Column('obtained_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_id'), 'test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_test_cases_test_plan_id'), 'test_cases', ['test_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_test_plan_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_test_plans_user_story_id'), table_name='test_plans')
    op.drop_index(op.f('ix_test_plans_id'), table_name='test_plans')
    op.drop_index(op.f('ix_test_plans_download_token'), table_name='test_plans')
    op.drop_table('test_plans')
    op.drop_index(op.f('ix_user_stories_story_id'), table_name='user_stories')
    op.drop_index(op.f('ix_user_stories_id'), table_name='user_stories')
    op.drop_table('user_stories')
    # ### end Alembic commands ###
