"""Add projects table and project_id to user_stories

Revision ID: fa625196223a
Revises: 65a797297c5f
Create Date: 2026-01-23 20:08:25.994601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa625196223a'
down_revision = '65a797297c5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Crear tabla projects (si no existe)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'projects' not in tables:
        op.create_table('projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
        op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    
    # 2. Crear proyecto AEROMAN por defecto (si no existe)
    result = conn.execute(sa.text("SELECT COUNT(*) FROM projects WHERE code = 'AEROMAN'"))
    if result.scalar() == 0:
        op.execute("""
            INSERT INTO projects (code, name, description, created_at)
            VALUES ('AEROMAN', 'AEROMAN', 'Proyecto por defecto para Test Plans existentes', CURRENT_TIMESTAMP)
        """)
    
    # 3. Verificar si project_id ya existe en user_stories
    columns = [col['name'] for col in inspector.get_columns('user_stories')]
    
    if 'project_id' not in columns:
        # Agregar project_id a user_stories (nullable primero)
        op.add_column('user_stories', sa.Column('project_id', sa.Integer(), nullable=True))
        
        # Asignar todos los user_stories existentes al proyecto AEROMAN
        op.execute("""
            UPDATE user_stories
            SET project_id = (SELECT id FROM projects WHERE code = 'AEROMAN')
            WHERE project_id IS NULL
        """)
        
        # Hacer project_id NOT NULL después de asignar valores
        op.alter_column('user_stories', 'project_id', nullable=False)
        
        # Crear índices y foreign key
        op.create_index(op.f('ix_user_stories_project_id'), 'user_stories', ['project_id'], unique=False)
        op.create_foreign_key('fk_user_stories_project', 'user_stories', 'projects', ['project_id'], ['id'])
    else:
        # Si project_id ya existe, asegurarse de que los NULL estén asignados a AEROMAN
        op.execute("""
            UPDATE user_stories
            SET project_id = (SELECT id FROM projects WHERE code = 'AEROMAN')
            WHERE project_id IS NULL
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_stories_project', 'user_stories', type_='foreignkey')
    op.drop_index(op.f('ix_user_stories_project_id'), table_name='user_stories')
    op.drop_column('user_stories', 'project_id')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
